### PR TITLE
Npm script

### PR DESCRIPTION
**Pull request by juddfranklin1**
Here is the branch I mentioned in Issue #1 . It has updated tests and I separated the cli script into its own file to avoid negatively impacting your existing code. My tests are maybe not the absolute best, but you can judge for yourself.

### CODE REVIEW

**Comment by juddfranklin1** [comment]
Even Travis likes my code. 🥇

**Comment by melanieseltzer** [comment]
Thanks for the PR! Unfortunately I cannot merge it in, for a few reasons:

- Requiring this cli as a dependency is a very unique situation. Most will install globally and not use npm scripts at all. Thus, I cannot justify including it in the package.

- cli_npm.js is duplicate functionality. It's also not transpiled with Babel.

- For your situation, the npm script should only be included in your **local** project's package.json (the one that's requiring this cli as a dependency), not in `getcoords-cli`'s package.json. 

For example, if you have a project called **foo** you would navigate into that folder and then:

```
$ npm install getcoords-cli
```

Then you would put this into **foo's** package.json:

```
"scripts": {
  "getcoords": "./node_modules/.bin/getcoords"
}
```

And then you would run your script, in the **foo** project:

```
$ npm run getcoords "some address"
```

**Comment by juddfranklin1** [comment]
Man, I wish I had those 2 hours back.

**Comment by melanieseltzer** [comment]
I appreciate your efforts regardless! You helped with figuring out how to get it running when it's not installed globally, which is always good info to know.

**Pull request closed without merging**
